// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZt-Zoi7OPNPnwovpxiaLQQ6SC73z1bZA',
    appId: '1:1042879000330:web:8cf6de72ece64e6e1754f3',
    messagingSenderId: '1042879000330',
    projectId: 'project1-24eab',
    authDomain: 'project1-24eab.firebaseapp.com',
    storageBucket: 'project1-24eab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6UzJwJF-krH2VyXFZnIJDv37fZ6D0-0',
    appId: '1:1042879000330:android:ca65fa0d86ce6c5a1754f3',
    messagingSenderId: '1042879000330',
    projectId: 'project1-24eab',
    storageBucket: 'project1-24eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUTvsP1O23_NXRkR-TNC9w54WEgg7PS0',
    appId: '1:1042879000330:ios:c21a32691de9c4441754f3',
    messagingSenderId: '1042879000330',
    projectId: 'project1-24eab',
    storageBucket: 'project1-24eab.appspot.com',
    iosClientId: '1042879000330-0gnkeo7tp7il5uho43jpaiir7rmu0nhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
